ESTATUS_ACTIVO = "ACTIVO"
ESTATUS_VACANTE = "VACANTE"
PERSONAL_ACTIVO = "ACTIVO"
PERSONAL_PASIVO = "PASIVO"
ESTATUS_PERMITIDOS = ["SUSPENDIDO", "BLOQUEADO", "ACTIVO"]
ESTATUS_PERMITIDOS_EGRESOS = ["PASIVO", "EGRESADO"]
