// import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ScrollArea } from "@/components/ui/scroll-area";
import { AuthController } from "@/components/auth-timer";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// ${geistSans.variable} ${geistMono.variable}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full ">
      <title>SAGP</title>
      <body
        className={` antialiased  bg-no-repeat  bg-[url('/bg.jpg')] backdrop-blur-[8px] bg-cover object-center overflow-hidden  h-full`}
      >
        <SessionProvider>
          {/* <AuthController /> */}
          <ScrollArea className="h-full w-full rounded-md">
            {children}
          </ScrollArea>
        </SessionProvider>
      </body>
    </html>
  );
}
